name: flutter_escaperank_web
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # My libraries!
  # -- Internationalization (multi language)
  flutter_i18n: ^0.32.0
  # -- Objects comparison
  equatable: ^2.0.0
  # -- Image compress to load faster
  flutter_image_compress: ^1.0.0
  # -- Path provider
  path_provider: ^2.0.2
  # -- Cached images
  cached_network_image: ^3.1.0
  # -- Web images combined with cached network images
  image_network: ^2.4.1+1
  # -- Shared Preferences
  shared_preferences: ^2.0.6
  # -- BLOC Pattern
  bloc: ^7.2.1
  flutter_bloc: ^7.3.0
  # -- Async functions
  async: ^2.5.0-nullsafety.3
  # -- Firebase libraries
  #firebase_messaging: ^10.0.8
  #firebase_core: ^1.0.0
  #firebase_analytics: ^8.3.3
  #firebase_auth: ^3.1.4
  # -- Launch URL
  url_launcher: ^6.0.12
  # To share an escape
  share_plus: ^3.0.2
  # Google maps
  # google_maps_flutter_web: ^0.3.2+1
  # Video Player
  video_player: ^2.2.5
  # Map and location
  geolocator: 7.1.0
  geocoding: ^2.0.1
  map: ^1.0.0
  # Carousel slider to display images
  carousel_slider: ^4.0.0
  # MapBox GL for flutter (because google_maps has no support on flutter web)
  mapbox_gl: ^0.15.0
  # Shimmer
  shimmer: ^2.0.0
  # Calendar carousel
  flutter_calendar_carousel: ^2.4.0
  # Checkbox Form Field
  checkbox_formfield: ^0.2.0
  # Linkify
  flutter_linkify: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/locales/
    - assets/images/devel_images/
  #  - assets/flutter_i18n/
  #  - assets/night_mode.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat_Regular
      fonts:
        - asset: assets/fonts/Montserrat_Regular.otf
    - family: Montserrat_Bold
      fonts:
        - asset: assets/fonts/Montserrat_Bold.otf
    - family: Montserrat_Semibold
      fonts:
        - asset: assets/fonts/Montserrat_Semibold.otf
    - family: Montserrat_Medium
      fonts:
        - asset: assets/fonts/Montserrat_Medium.otf
    - family: Kanit_Regular
      fonts:
        - asset: assets/fonts/Kanit_Regular.ttf
    - family: Kanit_Medium
      fonts:
        - asset: assets/fonts/Kanit_Medium.ttf
    - family: Kanit_Light
      fonts:
        - asset: assets/fonts/Kanit_Light.ttf
    - family: Kanit_Thin
      fonts:
        - asset: assets/fonts/Kanit_Thin.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
